### ISSUE TITLE
Delete Features/Menus that won't be used

### ISSUE THREAD

**Issue by JimFung** [timch326/ProjectFiveSymposium#1]
Remove all the features/menus from discourse that we won't be using. 
Please attach a list of the features removed in this thread.

**Comment by timch326** [comment]
### In the Menu (Hamburger) Dropdown
- Remove Badges > Go to Admin Settings, Basic Setup, Uncheck 'Enable the badge system'.

### Within Posts
- Remove Invite Button

### The Trust System
- Hide the attribute on the user profile 
- Set the default trust level system settings to be 4  - modify site_settings.yml!
