### ISSUE TITLE
Invite New Users

### ISSUE THREAD

**Issue by JimFung** [timch326/ProjectFiveSymposium#8]
i want....
- **Implement user type roles in invites and bulk invites**
- ~~Teachers~~ Admin can (bulk) invite a student to a group using built in invite tools
- ~~Teachers can invite mentors into groups as well~~
- ~~Teachers can only be created by super admin~~
- (Teachers don't have admin access)

**Comment by jesszhai** [comment]
Implemented drop down user role selection in user invite. The selection is saved to invites table upon send invite.
Bulk invites now takes user role fields in the file, user must specify a correct user role for each user
